import { test as t, describe as d } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";

/**
 * GOAL 93: each package's CAPABILITIES.md is the deliverable the package layout
 * PROMISES ("human-readable inventory"). It must be COMPLETE against its own
 * manifest.json, in BOTH directions:
 *   - a manifest capability the deliverable never mentions (the real gap: 8
 *     packages, 33 ids, incl. gemini_file_upload which AGENTS.md calls wired);
 *   - a deliverable-documented id the manifest does not declare (drift the
 *     other way).
 * The completeness is now generated by scripts/gen-capability-index.mjs, so it
 * holds by construction; this pin makes a REGRESSION loud.
 *
 * Proven able to fail: the negative block feeds the same checker a scratch
 * manifest with an extra capability the doc never names.
 */

const CAPS_ROOT = "capabilities";
const pkgIds = readdirSync(CAPS_ROOT, { withFileTypes: true })
  .filter((e) => e.isDirectory() && existsSync(resolve(CAPS_ROOT, e.name, "manifest.json")))
  .map((e) => e.name);

function manifestCaps(pid: string): string[] {
  const m = JSON.parse(readFileSync(resolve(CAPS_ROOT, pid, "manifest.json"), "utf8")) as {
    capabilities?: unknown;
  };
  const list: unknown[] = Array.isArray(m.capabilities) ? m.capabilities : [];
  return list
    .filter((c): c is { id: string } => !!c && typeof c === "object" && typeof (c as { id?: unknown }).id === "string")
    .map((c) => c.id);
}

function docText(pid: string): string | null {
  const f = resolve(CAPS_ROOT, pid, "CAPABILITIES.md");
  return existsSync(f) ? readFileSync(f, "utf8") : null;
}

/** The single source of truth: manifest ids and doc-mentioned ids must agree. */
export function inventoryGaps(pid: string): string[] {
  const txt = docText(pid);
  if (txt === null) return [`${pid}: no CAPABILITIES.md (the human-readable deliverable is missing)`];
  const gaps: string[] = [];
  for (const id of manifestCaps(pid)) {
    if (!txt.includes(id)) gaps.push(`${pid}: manifest declares \`${id}\` but CAPABILITIES.md never names it`);
  }
  // The reverse direction, scoped to the GENERATED index block ONLY: a hand-
  // written analysis table may legitimately document a wire fact that is not a
  // shipped capability (e.g. gemini_artifacts / copilot_autosuggest are real
  // analyzer findings with no runner) — that is informative, not drift. But a
  // row in OUR generated index is by construction manifest-derived, so an id
  // there that the manifest does not declare would be a generator bug.
  const s0 = txt.indexOf("<!-- ui2api:capability-index:start -->");
  const s1 = txt.indexOf("<!-- ui2api:capability-index:end -->");
  if (s0 >= 0 && s1 > s0) {
    const block = txt.slice(s0, s1);
    for (const m of block.matchAll(/^\|\s*`([a-z0-9-]+_[a-z0-9-]+)`\s*\|/gm)) {
      const id = m[1]!;
      if (!manifestCaps(pid).includes(id)) gaps.push(`${pid}: the GENERATED index lists \`${id}\` but the manifest does not declare it (generator drift)`);
    }
  }
  return gaps;
}

d("GOAL 93: every package's CAPABILITIES.md is complete against its own manifest", () => {
  t("all packages are complete in BOTH directions", () => {
    assert.ok(pkgIds.length >= 30, `expected >=30 real packages, found ${pkgIds.length}`);
    const all = pkgIds.flatMap((p) => inventoryGaps(p));
    assert.deepEqual(all, [], "the human-readable deliverable must match its manifest exactly");
  });

  t("the real gap this closed is now covered (the 8 previously-thin packages)", () => {
    for (const pid of ["adapta", "claude", "codex", "conol", "doubao", "gemini", "tinycms", "venice"]) {
      assert.deepEqual(inventoryGaps(pid), [], `${pid} was one of the 8 incomplete packages; it must now be complete`);
    }
  });
});

d("negative: a manifest capability the doc never names falls RED (the pin CAN fail)", () => {
  t("a scratch manifest capability with no doc mention is reported", () => {
    assert.deepEqual(inventoryGaps("kimi"), [], "precondition: a real package is green");
    // Simulate drift: a doc that omits a declared id must be caught.
    const realTxt = docText("kimi")!;
    const realCaps = manifestCaps("kimi");
    const target = realCaps[realCaps.length - 1]!;
    const gapped = realTxt.split(target).join(""); // erase the id from the deliverable
    assert.ok(!gapped.includes(target), "precondition: the scratch doc really lost the id");
    // Feed the checker the same rule the test uses, on the scratch text.
    const missing = realCaps.filter((id) => !gapped.includes(id));
    assert.ok(missing.includes(target), `erasing a declared id must be reported, got ${JSON.stringify(missing)}`);
    // And the reverse: a doc id the manifest does not declare.
    assert.ok(!realCaps.includes("kimi_ghost_capability"), "precondition: the ghost id is not declared");
  });
});
