import type { ActionMap } from "../types.js";

// Returns SKILL.md text describing the generated MCP server's tools so that
// skill-aware agents can discover and call them.
export function skillTemplate(map: ActionMap): string {
  const lines: string[] = [];
  lines.push("name: ui2api-" + map.host);
  lines.push("description: >-");
  lines.push(
    "  MCP tools generated by ui2api for " +
      map.host +
      " (" +
      map.url +
      "). Use the skill-loader.mjs to launch the stdio MCP server, then call these tools:"
  );
  lines.push("");
  lines.push("tools:");
  for (const a of map.actions) {
    lines.push("- " + a.name + ": " + a.description);
  }
  lines.push("");
  return lines.join("\n");
}

// Returns skill-loader.mjs that spawns the generated MCP server as a child
// process (node --import tsx index.ts) piping its stdio, so skill-aware agents
// can drive the server.
export function skillLoaderTemplate(): string {
  return `import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const serverPath = fileURLToPath(new URL("./index.ts", import.meta.url));

export function startServer(extraEnv = {}) {
  const child = spawn(process.execPath, ["--import", "tsx", serverPath], {
    stdio: ["pipe", "pipe", "inherit"],
    env: { ...process.env, ...extraEnv },
  });
  return child;
}

// If run directly, start the server and keep the process alive.
if (import.meta.url === \`file://\${process.argv[1]}\`) {
  const child = startServer();
  child.on("exit", (code) => process.exit(code ?? 0));
}
`;
}
